[package]
name = "rustbot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.12", default-features = false, features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
    "cache",
    "utils",
    "builder",
] }
poise = "0.6"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
env_logger = "0.10"
dotenv = "0.15"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
image = "0.24"
reqwest = { version = "0.11", features = ["stream"] }
gif = "0.12"
tempfile = "3.8"

[[bin]]
name = "rustbot"
path = "src/main.rs"
