version: "3.8"

services:
  rustbot:
    # Build locally with auto-update capability
    build: .
    container_name: rustbot
    restart: unless-stopped

    # Environment variables - CasaOS will override these
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RUST_LOG=${RUST_LOG:-info}
      - RUST_BACKTRACE=1

    # Minimal resource limits for CasaOS
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.5

    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "rustbot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Security (no read_only for git operations)
    security_opt:
      - no-new-privileges:true

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
