version: "3.8"

services:
  rustbot:
    image: deekahy/rustbot:latest
    container_name: rustbot-local
    restart: unless-stopped

    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - RUST_LOG=info

    # Use .env file for environment variables
    env_file:
      - .env

    # Resource limits for local testing
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

    # Health check to monitor bot status
    healthcheck:
      test: ["CMD", "pgrep", "rustbot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Networks
    networks:
      - rustbot-network

    # Labels for better organization
    labels:
      - "com.rustbot.environment=local"
      - "com.rustbot.service=discord-bot"

networks:
  rustbot-network:
    driver: bridge
    labels:
      - "com.rustbot.environment=local"
